spring:
  application:
    name: spartaEats
  datasource:
    url: jdbc:postgresql://team15.c7sy6kkiaivz.ap-southeast-2.rds.amazonaws.com/spartaEats
    username: team15
    password: spartateam15!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

server:
  port: 9080

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==